# Generated by Django 4.0.3 on 2022-04-20 07:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ucoins_count', models.PositiveSmallIntegerField()),
                ('description', models.TextField(max_length=400)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Активности',
                'verbose_name_plural': 'Активность',
                'ordering': ['created_date'],
                'get_latest_by': 'created_date',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('category', models.CharField(db_index=True, max_length=25)),
                ('price', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=400)),
                ('photo', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукт',
                'ordering': ['name'],
                'get_latest_by': 'created_date',
            },
        ),
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('EE', 'Employee'), ('MR', 'Moderator'), ('AR', 'Administrator')], db_index=True, default='EE', max_length=2)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex=re.compile('\\+{0,1}[78]\\d{10}'))])),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(blank=True, max_length=70, null=True)),
                ('about_me', models.TextField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Информация о пользователях',
                'verbose_name_plural': 'Информация о пользователе',
            },
        ),
        migrations.CreateModel(
            name='UcoinsRequests',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activities')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запросы',
                'verbose_name_plural': 'Запрос',
                'ordering': ['created_date'],
                'get_latest_by': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_list', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('office_address', models.CharField(choices=[('LA', 'ул. Ленина, 45а'), ('MA', 'ул. Мира, 32'), ('YA', 'ул. Ясная, 12')], default='LA', max_length=2)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказ',
                'ordering': ['created_date'],
                'get_latest_by': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзины',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
