# Generated by Django 4.0.3 on 2022-04-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_activities_options_alter_carts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='products_list',
            field=models.TextField(),
        ),
    ]
