# Generated by Django 4.0.3 on 2022-04-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_orders_products_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='products_list',
            field=models.BinaryField(),
        ),
    ]
