# Generated by Django 4.0.3 on 2022-05-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='user_id',
        ),
    ]
