# Generated by Django 4.0.3 on 2022-05-10 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_rename_activities_activity_rename_carts_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('AD', 'Add'), ('EX', 'Expenses')], db_index=True, default='AD', max_length=2)),
                ('category', models.CharField(choices=[('RQ', 'Requests'), ('OR', 'Orders'), ('PR', 'Presents')], db_index=True, default='PR', max_length=2)),
                ('category_id', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История баланса',
                'verbose_name_plural': 'История баланса',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from', models.IntegerField()),
                ('text', models.TextField(max_length=500)),
                ('ucoin_count', models.IntegerField()),
                ('background', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('SN', 'Sent'), ('RC', 'Received')], db_index=True, default='SN', max_length=2)),
                ('user_to', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подарок',
                'verbose_name_plural': 'Подарки',
                'ordering': ['-created_date'],
            },
        ),
        migrations.DeleteModel(
            name='UserHistory',
        ),
        migrations.AlterModelOptions(
            name='ucoinrequest',
            options={'get_latest_by': ['created_date'], 'ordering': ['-created_date'], 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('CM', 'Completed'), ('IR', 'In progress')], db_index=True, default='IR', max_length=2),
        ),
        migrations.AddField(
            model_name='ucoinrequest',
            name='rejected_comment',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='ucoinrequest',
            name='state',
            field=models.CharField(choices=[('AC', 'Accepted'), ('RJ', 'Rejected'), ('IR', 'In progress')], db_index=True, default='IR', max_length=2),
        ),
    ]
