# Generated by Django 4.0.3 on 2022-05-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_balancehistory_present_delete_userhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phone_number',
        ),
    ]
