# Generated by Django 4.0.3 on 2022-05-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_userinfo_about_me_remove_userinfo_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ucoinrequest',
            unique_together=set(),
        ),
    ]
